In [1]:
from create_working_df import merged_rating_beer
import os
import pandas as pd

In [2]:
path = '../../data/baseData/minimizedData/'

In [3]:
BA_beer_loc, BA_rating_loc, RB_beer_loc, RB_rating_loc, BA_ratbeer, RB_ratbeer = merged_rating_beer(path)

In [5]:
RB_ratbeer.head(100)

,Unnamed: 0,beer_name,beer_id,brewery_name,brewery_id,style,user_id,appearance,aroma,palate,taste,overall,rating,user_location,avg,beer_location
0,0,33 Export (Gabon),410549,Sobraga,3198,Pale Lager,175852,2.0,4.0,2.0,4.0,8.0,2.0,Poland,2.72,Gabon
1,1,Castel Beer (Gabon),105273,Sobraga,3198,Pale Lager,442761,2.0,3.0,2.0,4.0,8.0,1.9,Spain,2.18,Gabon
2,2,Castel Beer (Gabon),105273,Sobraga,3198,Pale Lager,288889,3.0,3.0,2.0,3.0,5.0,1.6,Poland,2.18,Gabon
3,3,Castel Beer (Gabon),105273,Sobraga,3198,Pale Lager,250510,4.0,3.0,1.0,2.0,5.0,1.5,Spain,2.18,Gabon
4,4,Castel Beer (Gabon),105273,Sobraga,3198,Pale Lager,122778,2.0,4.0,2.0,4.0,7.0,1.9,Germany,2.18,Gabon
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,Boundary A Berliner Vice #2,386909,Boundary,22818,Berliner Weisse,36509,3.0,7.0,3.0,6.0,13.0,3.2,Scotland,3.35,Northern Ireland
96,96,Boundary A Berliner Vice #2,386909,Boundary,22818,Berliner Weisse,47143,3.0,8.0,3.0,7.0,15.0,3.6,Israel,3.35,Northern Ireland
97,97,Boundary a Berliner Vice #3,364610,Boundary,22818,Berliner Weisse,150807,2.0,6.0,4.0,8.0,16.0,3.6,Scotland,3.20,Northern Ireland
98,98,Boundary a Berliner Vice #3,364610,Boundary,22818,Berliner Weisse,178977,3.0,7.0,3.0,6.0,13.0,3.2,Scotland,3.20,Northern Ireland
99,99,Boundary a Berliner Vice #3,364610,Boundary,22818,Berliner Weisse,128401,3.0,7.0,3.0,7.0,14.0,3.4,Scotland,3.20,Northern Ireland

In [8]:
BA_ratbeer[BA_ratbeer['user_location'] == BA_ratbeer['beer_location']].head(300)

,Unnamed: 0,beer_name,beer_id,brewery_name,brewery_id,style,user_id,appearance,aroma,palate,taste,overall,rating,user_location,avg,beer_location
2,2,Barelegs Brew,19590,Strangford Lough Brewing Company Ltd,10093,English Pale Ale,mdagnew.19527,4.0,3.5,3.5,4.0,3.5,3.73,Northern Ireland,3.85,Northern Ireland
3,3,Barelegs Brew,19590,Strangford Lough Brewing Company Ltd,10093,English Pale Ale,helloloser12345.10867,4.0,3.5,4.0,4.0,4.5,3.98,Northern Ireland,3.85,Northern Ireland
4,4,Barelegs Brew,19590,Strangford Lough Brewing Company Ltd,10093,English Pale Ale,cypressbob.3708,4.0,4.0,4.0,4.0,4.0,4.00,Northern Ireland,3.85,Northern Ireland
77,77,Legbiter,19827,Strangford Lough Brewing Company Ltd,10093,English Pale Ale,mdagnew.19527,4.0,4.5,3.5,4.0,3.5,3.97,Northern Ireland,3.45,Northern Ireland
79,79,Legbiter,19827,Strangford Lough Brewing Company Ltd,10093,English Pale Ale,cypressbob.3708,4.5,4.5,4.5,4.0,4.0,4.20,Northern Ireland,3.45,Northern Ireland
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11898,11898,Innis And Gunn Original Oak Aged Beer,12719,Innis & Gunn,10272,Scottish Ale,wastedyouth.716571,NaN,NaN,NaN,NaN,NaN,4.00,Scotland,3.75,Scotland
12097,12097,Innis And Gunn Original Oak Aged Beer,12719,Innis & Gunn,10272,Scottish Ale,hanglow.660363,NaN,NaN,NaN,NaN,NaN,2.00,Scotland,3.75,Scotland
12228,12228,Innis And Gunn Original Oak Aged Beer,12719,Innis & Gunn,10272,Scottish Ale,micky67.655089,NaN,NaN,NaN,NaN,NaN,3.50,Scotland,3.75,Scotland
12353,12353,Innis And Gunn Original Oak Aged Beer,12719,Innis & Gunn,10272,Scottish Ale,shearer292.603248,4.5,4.5,4.0,4.5,4.5,4.45,Scotland,3.75,Scotland
12366,12366,Innis And Gunn Original Oak Aged Beer,12719,Innis & Gunn,10272,Scottish Ale,flyingpig.524986,4.5,4.5,4.0,4.0,4.0,4.15,Scotland,3.75,Scotland

In [4]:
def get_var_name(var):
    for name, value in globals().items():
        if value is var:
            return name

In [5]:
def save_csv_with_directory_check(df, file_path):
    directory = os.path.dirname(file_path)
    
    if not os.path.exists(directory):
        os.makedirs(directory)
    
    df.to_csv(file_path, index=False)
    print(f"CSV saved to {file_path}")

In [7]:
save_csv_with_directory_check(BA_beer_loc, 'data/baseData/Modified/' + get_var_name(BA_beer_loc) + '.csv')
save_csv_with_directory_check(BA_rating_loc, 'data/baseData/Modified/' + get_var_name(BA_rating_loc) + '.csv')
save_csv_with_directory_check(RB_beer_loc, 'data/baseData/Modified/' + get_var_name(RB_beer_loc) + '.csv')
save_csv_with_directory_check(RB_rating_loc, 'data/baseData/Modified/' + get_var_name(RB_rating_loc) + '.csv')
save_csv_with_directory_check(BA_ratbeer, 'data/baseData/Modified/' + get_var_name(BA_ratbeer) + '.csv')
save_csv_with_directory_check(RB_ratbeer, 'data/baseData/Modified/' + get_var_name(RB_ratbeer) + '.csv')

CSV saved to data/baseData/Modified/BA_beer_loc.csv
CSV saved to data/baseData/Modified/BA_rating_loc.csv
CSV saved to data/baseData/Modified/RB_beer_loc.csv
CSV saved to data/baseData/Modified/RB_rating_loc.csv
CSV saved to data/baseData/Modified/BA_ratbeer.csv
CSV saved to data/baseData/Modified/RB_ratbeer.csv

In [11]:
BA_ratbeer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8393032 entries, 0 to 8393031
Data columns (total 16 columns):
 #   Column         Dtype
---  ------         -----
 0   Unnamed: 0     int64
 1   beer_name      string
 2   beer_id        int64
 3   brewery_name   string
 4   brewery_id     int64
 5   style          string
 6   user_id        string
 7   appearance     float64
 8   aroma          float64
 9   palate         float64
 10  taste          float64
 11  overall        float64
 12  rating         float64
 13  user_location  string
 14  avg            float64
 15  beer_location  string
dtypes: float64(7), int64(3), string(6)
memory usage: 1.0 GB

In [10]:
BA_ratbeer.head()

,Unnamed: 0,beer_name,beer_id,brewery_name,brewery_id,style,user_id,appearance,aroma,palate,taste,overall,rating,user_location,avg,beer_location
0,0,RÃ©gab,142544,Societe des Brasseries du Gabon (SOBRAGA),37262,Euro Pale Lager,nmann08.184925,3.25,2.75,3.25,2.75,3.0,2.88,"United States, Washington",2.88,Gabon
1,1,Barelegs Brew,19590,Strangford Lough Brewing Company Ltd,10093,English Pale Ale,stjamesgate.163714,3.00,3.50,3.50,4.00,3.5,3.67,"United States, New York",3.85,Northern Ireland
2,2,Barelegs Brew,19590,Strangford Lough Brewing Company Ltd,10093,English Pale Ale,mdagnew.19527,4.00,3.50,3.50,4.00,3.5,3.73,Northern Ireland,3.85,Northern Ireland
3,3,Barelegs Brew,19590,Strangford Lough Brewing Company Ltd,10093,English Pale Ale,helloloser12345.10867,4.00,3.50,4.00,4.00,4.5,3.98,Northern Ireland,3.85,Northern Ireland
4,4,Barelegs Brew,19590,Strangford Lough Brewing Company Ltd,10093,English Pale Ale,cypressbob.3708,4.00,4.00,4.00,4.00,4.0,4.00,Northern Ireland,3.85,Northern Ireland