In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import math

In [2]:
#out of exploration out of src
beers = pd.read_csv('../../baseData/matched_beer_data/beers.csv')

print(beers.shape)
beers.drop_duplicates(inplace=True)
print(beers.columns)
print(beers.shape)
beers.sample(10)

C:\Users\Enzo\AppData\Local\Temp\ipykernel_7040\622460849.py:2: DtypeWarning: Columns (0,1,2,3,4,5,8,10,11,12,13,15,16,17,18,19,20,23,25,26,27,29,30,31,32) have mixed types. Specify dtype option on import or set low_memory=False.
  beers = pd.read_csv('../../baseData/matched_beer_data/beers.csv')

(45641, 33)
Index(['ba', 'ba.1', 'ba.2', 'ba.3', 'ba.4', 'ba.5', 'ba.6', 'ba.7', 'ba.8',
       'ba.9', 'ba.10', 'ba.11', 'ba.12', 'ba.13', 'ba.14', 'ba.15', 'rb',
       'rb.1', 'rb.2', 'rb.3', 'rb.4', 'rb.5', 'rb.6', 'rb.7', 'rb.8', 'rb.9',
       'rb.10', 'rb.11', 'rb.12', 'rb.13', 'rb.14', 'scores', 'scores.1'],
      dtype='object')
(45641, 33)

,ba,ba.1,ba.2,ba.3,ba.4,ba.5,ba.6,ba.7,ba.8,ba.9,...,rb.7,rb.8,rb.9,rb.10,rb.11,rb.12,rb.13,rb.14,scores,scores.1
5254,7.1,3.86,3.86,3.86,NaN,90085,Flying Monkeys Lucille Robust Porter,Porter Robust Lucille,10796,Flying Monkeys Craft Brewery,...,5547,Flying Monkeys Craft Brewery,1,1,NaN,Porter,NaN,-0.17420287472929763,0.6681870471541169,1.0
9590,4.6,2.96,2.96,NaN,NaN,210895,The Mayne Thing Golden Ale,Ale Thing Mayne Golden The,43118,Newstead Brewing Co.,...,18363,Newstead Brewing,15,15,41.0,Golden Ale/Blond Ale,66.0,-0.6138130789285108,0.5616302702731728,1.0000000000000002
36943,5.6,NaN,NaN,NaN,NaN,253084,From The Thumb Porter,The From Thumb Porter,46531,Silver Harbor Brewing Company,...,27479,Silver Harbor Brewing Company,0,0,NaN,Porter,NaN,NaN,0.798921,1.0
8358,5.3,3.55,3.45,3.6,NaN,89516,Gutenberg Original Hefe-Weissbier,Original HefeWeissbier Gutenberg,7589,Einsiedler Brauhaus GmbH,...,1727,Einsiedler Brauhaus,24,24,30.0,German Hefeweizen,38.0,-0.9000377041852864,0.4001787377349988,1.0
20092,6.0,3.99,4.066667,3.895,NaN,151139,Snow Day,Snow Day,36497,Old Colony Brewing,...,20151,Old Colony Brewing,0,0,NaN,Spice/Herb/Vegetable,NaN,NaN,1.0,1.0
1839,4.2,3.56,3.56,3.56,NaN,287248,Yellow Peak,Peak Yellow,42842,Torrside Brewing,...,24653,Torrside Brewing,5,5,NaN,American Pale Ale,NaN,0.04405519190468902,1.0000000000000002,1.0000000000000002
9940,5.2,3.69,3.85,3.58,NaN,194760,APA,APA,42696,Cartujana Cerveza Artesana,...,23951,Cartujana Cerveza Artesana,4,4,NaN,American Pale Ale,NaN,-0.09061362408905756,1.0,1.0
32593,5.6,NaN,NaN,NaN,NaN,286825,That’s The Way Love Gose,That’s Way Love Gose The,44994,Boiler Brewing Co.,...,26401,Boiler Brewing Company,2,2,NaN,Grodziskie/Gose/Lichtenhainer,NaN,-1.382858,0.681447,1.0
31756,6.0,3.96,3.635,4.17,NaN,273568,Tropicalus,Tropicalus,36080,Lenny Boy Brewing Co.,...,19711,Lenny Boy Brewing Company,1,1,NaN,India Pale Ale (IPA),NaN,-0.217862,1.0,1.0
11574,6.5,3.52,3.456666666666666,3.5755555555555563,82.0,111421,Enlightenment: The Age Of Raisin,Raisin Of Enlightenment The Age,16534,Renaissance Brewing,...,6595,Renaissance Brewing,47,47,75.0,Belgian Ale,88.0,-0.025592808266336455,0.7010196653666418,0.9761298532204604

It seems like they've inner merged RateBeer and BeerAdvocate csvs, lets test that...

In [3]:
#out of exploration out of src
beers_BA = pd.read_csv('../../baseData/BeerAdvocate/beers.csv')


#out of exploration out of src
beers_RB = pd.read_csv('../../baseData/RateBeer/beers.csv')

merged_BA_RB = pd.merge(beers_BA,beers_RB, how='inner')
merged_BA_RB
beer_wout_brewery_name

Empty DataFrame
Columns: [beer_id, beer_name, brewery_id, brewery_name, style, nbr_ratings, nbr_reviews, avg, ba_score, bros_score, abv, avg_computed, zscore, nbr_matched_valid_ratings, avg_matched_valid_ratings, overall_score, style_score]
Index: []