In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import math

In [2]:
import os
print(os.getcwd())

c:\Users\Enzo\Desktop\ada-2024-project-x0x0\src\exploration

## Looking at BeerAdvocate

In [3]:
#out of exploration out of src
beers = pd.read_csv('../../baseData/BeerAdvocate/beers.csv')

print(beers.shape)
beers.drop_duplicates(inplace=True)
print(beers.columns)
print(beers.shape)
beers.sample(10)

(280823, 15)
Index(['beer_id', 'beer_name', 'brewery_id', 'brewery_name', 'style',
       'nbr_ratings', 'nbr_reviews', 'avg', 'ba_score', 'bros_score', 'abv',
       'avg_computed', 'zscore', 'nbr_matched_valid_ratings',
       'avg_matched_valid_ratings'],
      dtype='object')
(280823, 15)

,beer_id,beer_name,brewery_id,brewery_name,style,nbr_ratings,nbr_reviews,avg,ba_score,bros_score,abv,avg_computed,zscore,nbr_matched_valid_ratings,avg_matched_valid_ratings
241896,102949,South Pacific Brown,29682,Kauai Island Brewery & Grill,American Brown Ale,9,1,3.64,NaN,NaN,3.8,3.585556,NaN,0,NaN
141794,189139,Black Saison,34426,Jailbreak Brewing Company,Saison / Farmhouse Ale,1,0,3.25,NaN,NaN,5.6,3.250000,NaN,0,NaN
237446,234651,Paisan Porter,43242,JD's Sports Bar and Brewery,American Porter,1,0,3.04,NaN,NaN,5.0,3.040000,NaN,0,NaN
78900,203010,Apricot Wheat,30298,Roseville Brewing Company,Fruit / Vegetable Beer,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
112334,93099,Chico Suave,14,Cambridge Brewing Company,American IPA,4,2,4.13,NaN,NaN,4.8,4.175000,NaN,0,NaN
238801,19561,Anniversary Tripel,818,McKenzie Brewing Company,Tripel,1,1,3.31,NaN,NaN,NaN,3.310000,NaN,0,NaN
233136,291649,Gaelforce IPA,48115,Drumconrath Brewing Company,American IPA,1,0,3.77,NaN,NaN,6.2,3.770000,-0.515113,0,NaN
51242,9681,Diekirch Grande Réserve,2697,Brasserie de Luxembourg Mousel -Diekirch SA,Munich Dunkel Lager,1,1,2.97,NaN,NaN,6.9,2.970000,NaN,0,NaN
111982,45844,Samuel Adams Harvest Pumpkin Ale,35,Boston Beer Company (Samuel Adams),Pumpkin Ale,2635,648,3.58,81.0,72.0,5.7,3.469696,NaN,0,NaN
23484,237741,Blonde Saison,46250,Kettle River Brewing Co.,Saison / Farmhouse Ale,0,0,NaN,NaN,NaN,3.9,NaN,NaN,0,NaN

In [4]:
#out of exploration out of src
breweries = pd.read_csv('../../baseData/BeerAdvocate/breweries.csv')

print(breweries.shape)
breweries.drop_duplicates(inplace=True)
print(breweries.columns)
print(breweries.shape)
breweries.sample(10)

(16758, 4)
Index(['id', 'location', 'name', 'nbr_beers'], dtype='object')
(16758, 4)

,id,location,name,nbr_beers
15735,13658,"Canada, Ontario",Draft Horse Brewery / Navan Feed Mill Restaurant,0
15482,4384,"United States, Montana",Lightning Boy Brewery,1
13177,44401,"United States, Michigan",Kilkenny's Irish Public House,0
9612,47435,"United States, New Jersey",Troon Brewing,30
4489,16829,Germany,Bayreuther Bierbrauerei,14
15617,14916,"Canada, Quebec",Les Brasseurs du Hameau,47
14501,321,Belgium,Brasserie d'Achouffe,20
3556,7613,Germany,Wittichenauer Stadtbrauerei,1
3496,5860,Germany,Brauerei Xaver Wasserburger,0
8776,35011,"United States, California",Sundowner Brewery,32

In [5]:
#out of exploration out of src
users = pd.read_csv('../../baseData/BeerAdvocate/users.csv')

print(users.shape)
users.drop_duplicates(inplace=True)
print(users.columns)
print(users.shape)
users.sample(10)

(153704, 6)
Index(['nbr_ratings', 'nbr_reviews', 'user_id', 'user_name', 'joined',
       'location'],
      dtype='object')
(153704, 6)

,nbr_ratings,nbr_reviews,user_id,user_name,joined,location
11460,4,0,crazybrody.706269,crazybrody,1.354705e+09,"United States, Indiana"
5261,9,2,wwwagainsttimeca.1149511,wwwagainsttimeca,1.464430e+09,Canada
22094,438,0,seaale.682156,SeaAle,1.340532e+09,"United States, Oregon"
57588,2,0,jake095.919394,jake095,1.420283e+09,NaN
88755,1,0,mountainmaniac.438398,MountainManiac,1.268651e+09,"United States, Colorado"
111826,3,1,jelpernw.408660,jelpernw,1.261825e+09,"United States, New York"
86106,15,0,sethberry.938950,Sethberry,1.423048e+09,NaN
33526,6,2,fivebyfive.793394,FiveByFive,1.397038e+09,Canada
94272,1,0,tagyoureit24824.919262,tagyoureit24824,1.420283e+09,NaN
58931,1,0,thefearedbeard.707199,TheFearedBeard,1.355224e+09,NaN

In [8]:
#there are 151 million lines of text... thats a lot
def parse_ratings_file(file_path, limit):
    data = []
    current_block = []
    i = 0

    with open(file_path, 'r') as file:  
        for line in file:
            i += 1
            
            if i%1_000_000 == 0: print('line x million: ', i/1_000_000)
            if i > limit :
                print('Saved first ' + str(limit/1_000_000) + ' million lines')
                break
            
            line = line.strip()  # Remove leading/trailing whitespace
            
            if not line: #if empty line, '' treated as false
                data.append(current_block)
                current_block = []
                continue #next iteration of loop
            
            if ': ' in line:  
                key, value = line.split(': ', 1)  # Split by the first occurrence of ': '
                current_block.append(value)
            

    # Convert the list of lists to a DataFrame
    return pd.DataFrame(data)


ratings_df = parse_ratings_file('../../baseData/BeerAdvocate/ratings.txt', limit = 10_000_000)

#since our txt file is in a predicatble format we can make things easy on ourselves
new_column_names = [
    'beer_name',
    'beer_id',
    'brewery_name',  
    'brewery_id',    
    'style',         
    'abv',           
    'date',          
    'user_name',     
    'user_id',       
    'appearance',    
    'aroma',         
    'palate',        
    'taste',         
    'overall',       
    'rating',        
    'text',
    'review'
]

ratings_df.columns =  new_column_names
# Display the first few rows of the DataFrame
ratings_df.sample(10)

line x million:  1.0
line x million:  2.0
line x million:  3.0
line x million:  4.0
line x million:  5.0
line x million:  6.0
line x million:  7.0
line x million:  8.0
line x million:  9.0
line x million:  10.0
Saved first 10.0 million lines

,beer_name,beer_id,brewery_name,brewery_id,style,abv,date,user_name,user_id,appearance,aroma,palate,taste,overall,rating,text,review
158629,Original Flag Porter,14563,Darwin Brewery Ltd.,935,English Porter,5.0,1107169200,rkhaze,rkhaze.2969,4.0,4.5,4.0,4.0,4.0,4.12,Pours out a light mahogany color with a big cr...,True
16077,Blackfriar,14518,"Inveralmond Brewery Ltd., The",1108,Scottish Ale,7.0,1248084000,popery,popery.196587,4.0,3.5,4.0,4.0,4.0,3.88,Dark amber brown liquid decent lacing. The nos...,True
19107,McEwan's Export,4587,The Caledonian Brewing Company,188,Scottish Ale,4.5,1092218400,cypressbob,cypressbob.3708,3.5,4.0,4.0,3.0,4.0,3.57,"Standard can, redPours with a brown body, slig...",True
91406,Samuel Smith's The Famous Taddy Porter,572,Samuel Smith Old Brewery (Tadcaster),113,English Porter,5.0,1333274400,jk3,jk3.638051,nan,nan,nan,nan,nan,4.00,nan,False
138492,Fuller's London Porter,221,Fuller Smith & Turner PLC,71,English Porter,5.4,1416308400,Arriskuwonder,arriskuwonder.793725,nan,nan,nan,nan,nan,4.25,nan,False
198723,Iron Maiden Trooper,96511,Robinsons Family Brewers,23394,Extra Special / Strong Bitter (ESB),4.7,1398247200,BrazilianAussie,brazilianaussie.660776,nan,nan,nan,nan,nan,3.25,nan,False
453400,Side Launch Colossus,148873,Side Launch Brewing Company,34726,Dunkelweizen,8.0,1435658400,TheSevenDuffs,thesevenduffs.417825,3.75,3.75,3.75,3.75,3.75,3.75,nan,False
388621,Old Yale Pale Ale,13670,Old Yale Brewing Co.,3711,American Pale Ale (APA),5.0,1459418400,GlendonTT,glendontt.810901,3.75,3.5,3.75,3.5,3.5,3.54,nan,False
396844,Flying Monkeys Netherworld Cascadian Dark Ale,53832,Flying Monkeys Craft Brewery,10796,American Black Ale,6.0,1386932400,Noxious26,noxious26.22115,4.5,4.25,3.0,3.75,3.75,3.84,355ml brown bottle poured in a pint glass. Pur...,True
210902,Dos Equis Amber Lager,171,"Cervecería Cuauhtémoc Moctezuma, S.A. de C.V.",57,Vienna Lager,4.7,1339063200,hardcor33,hardcor33.534622,nan,nan,nan,nan,nan,3.00,nan,False

In [11]:
#reviews.txt is ratings.txt but only where there are reviews, (review: True)
#there are 45 million lines of text... thats a lot
def parse_ratings_file(file_path, limit):
    data = []
    current_block = []
    i = 0

    with open(file_path, 'r') as file:  
        for line in file:
            i += 1
            
            if i%1_000_000 == 0: print('line x million: ', i/1_000_000)
            if i > limit :
                print('Saved first ' + str(limit/1_000_000) + ' million lines')
                break
            
            line = line.strip()  # Remove leading/trailing whitespace
            
            if not line: #if empty line, '' treated as false
                data.append(current_block)
                current_block = []
                continue #next iteration of loop
            
            if ': ' in line:  
                key, value = line.split(': ', 1)  # Split by the first occurrence of ': '
                current_block.append(value)
            

    # Convert the list of lists to a DataFrame
    return pd.DataFrame(data)


ratings_df = parse_ratings_file('../../baseData/BeerAdvocate/reviews.txt', limit = 10_000_000)

#since our txt file is in a predicatble format we can make things easy on ourselves
new_column_names = [
    'beer_name',
    'beer_id',
    'brewery_name',  
    'brewery_id',    
    'style',         
    'abv',           
    'date',          
    'user_name',     
    'user_id',       
    'appearance',    
    'aroma',         
    'palate',        
    'taste',         
    'overall',       
    'rating',        
    'text',
]

ratings_df.columns =  new_column_names
# Display the first few rows of the DataFrame
ratings_df.sample(10)

line x million:  1.0
line x million:  2.0
line x million:  3.0
line x million:  4.0
line x million:  5.0
line x million:  6.0
line x million:  7.0
line x million:  8.0
line x million:  9.0
line x million:  10.0
Saved first 10.0 million lines

,beer_name,beer_id,brewery_name,brewery_id,style,abv,date,user_name,user_id,appearance,aroma,palate,taste,overall,rating,text
252436,DAB Original,2831,Dortmunder Actien Brauerei / DAB,726,Dortmunder / Export Lager,5.0,1103281200,mynie,mynie.6910,3.0,3.5,3.5,3.0,2.0,2.97,&quot;The Beer of World Fame.&quot;Okay.Pours ...
469894,Native Ale,6663,New Glarus Brewing Company,590,English Brown Ale,5.0,1118570400,Sixpoint,sixpoint.7531,3.5,4.0,3.5,4.0,4.5,4.02,Is &quot;SLAMMABLE&quot; a word? It is if you'...
462230,Summarillo,176189,Central Waters Brewing Co.,652,American Pale Lager,5.2,1438596000,jzlyo,jzlyo.663004,3.75,4.0,4.0,4.0,4.0,3.99,"Aroma is pine, tropical fruit and mildly grain..."
248343,Schneider Weisse Tap 6 Unser Aventinus,224,Weisses Bräuhaus G. Schneider & Sohn GmbH,72,Weizenbock,8.2,1190800800,jtrockchalk,jtrockchalk.99303,4.0,4.0,4.0,4.5,4.0,4.20,First review.A - Dark brown like a grade B map...
230404,Black Tie,59285,Mikkeller ApS,13307,American Double / Imperial Stout,11.5,1332756000,BlastBeats,blastbeats.584434,4.0,5.0,4.5,4.0,4.0,4.29,Poured this bottle of Black Tie into my Mikkel...
440145,Leinie's Amber Light,3776,Jacob Leinenkugel Brewing Company,710,Light Lager,nan,1122372000,bditty187,bditty187.531,4.0,3.0,3.0,3.5,3.0,3.26,"Golden-amber in hue, a steady stream of animat..."
33720,Samuel Smith's India Ale,573,Samuel Smith Old Brewery (Tadcaster),113,English India Pale Ale (IPA),5.0,1129975200,Holyterror,holyterror.5015,3.5,3.5,3.5,4.0,4.0,3.80,SS's India Ale poured a medium copper with a s...
249474,Schneider Weisse Tap 7 Unser Original,3280,Weisses Bräuhaus G. Schneider & Sohn GmbH,72,Hefeweizen,5.4,1214647200,Brianmerrilyn,brianmerrilyn.136551,4.0,4.0,4.0,4.5,4.0,4.20,16.9 oz. poured into mini heffe glass...many t...
416459,Guinness Draught,754,Guinness Ltd.,209,Irish Dry Stout,4.2,1290164400,BeerdedEric,beerdederic.510922,4.0,2.5,4.0,3.5,3.5,3.34,Poured halfway into a mug from a can and poure...
1993,Ola Dubh Special Reserve 12,41037,Harviestoun Brewery Ltd.,323,Old Ale,8.0,1372932000,dwren89,dwren89.648710,4.5,4.0,4.5,4.75,4.5,4.48,"Appearance: Pitch black, tan head, but disinte..."